podName: demandagent
image:
  repository: 
  tag: 
  pullPolicy: 

# agent type or tag 

type : 

env:
  useSecret: true
  secretName: 
  directValues: 
    AZP_URL: 
    AZP_TOKEN: 
    AZP_POOL : 

serviceAccount:
  exists: false
  name: 

imagePullSecrets:
  exists: true
  name: 


hostAliases:
  required : false
  # example below 
  hosts:
  - ip: "172.16.40.21"
    hostnames:
      - "azuredevops.local"