podName: demandagent
image:
  repository: matrek/demand-java-agent
  tag: 1.1
  pullPolicy: IfNotPresent


# agent type or tag 

type: java

env:
  useSecret: true
  secretName: azdevops
  directValues: 
    AZP_URL: 
    AZP_TOKEN: 
    AZP_POOL : 

serviceAccount:
  exists: false
  name: 

imagePullSecrets:
  exists: true
  name: regcred


hostAliases:
  required : true
  # example below 
  hosts:
  - ip: "172.16.40.21"
    hostnames:
      - "azuredevops.local"